//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBIZZ.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTaxgroupDetail
    {
        public int PurchaseTaxgroupDetailsId { get; set; }
        public Nullable<long> PurchaseTaxGroupId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
    
        public virtual PurchaseTaxGroup PurchaseTaxGroup { get; set; }
        public virtual TaxType TaxType { get; set; }
    }
}
