//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBIZZ.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int settingId { get; set; }
        public Nullable<int> Decimal_Places { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<bool> Enable_Invoice_Tax { get; set; }
        public Nullable<bool> Print_Tin_on_Invoice { get; set; }
        public Nullable<bool> Print_address { get; set; }
        public string InvoiceTemplateName { get; set; }
        public string PaperSize { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
