//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSBIZZ.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingId { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<bool> EnableInvoiceTax { get; set; }
        public Nullable<bool> PrintTinOnInvoice { get; set; }
        public Nullable<bool> PrintAddress { get; set; }
        public string InvoiceTemplateName { get; set; }
        public string PaperSize { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
